version: "3.1"
services:
  redis-urlshortner:
    container_name: redis-urlshortner
    image: redis:latest
    command: ["redis-server", "--bind", "redis-urlshortner", "--port", "6379"]
    hostname: redis-urlshortner
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  url-shortner:
    container_name: url-shortner
    image: phanibushan/url-shortner:latest
    ports:
      - 80:80
    environment:
      - spring_redis_host=redis-urlshortner
      - server_port=80
    depends_on:
      - redis-urlshortner

volumes:
  redis_data:
    driver: local